### ISSUE TITLE
Instructions how to set up the first node and config the pi on first time logging in

### ISSUE THREAD

**Issue by Natomac** [ulno/ulnoiot#10]
It would be nice to have a link that walks you through setting up your frist node the first time you logging to ulnoiot via both ssh or webpage.
Also a link to how to config your access point.

**Comment by ulno** [comment]
A link, a website, a tutorial, an automatic script like raspi-config?
Or do you just mean a link in the initial webpage you see, when you open the pi's webpage?

**Comment by ulno** [comment]
Is mainly done, maybe some images and a link to a video would be helpful.

**Comment by ulno** [comment]
will not be fixed here, check https://github.com/iotempire/iotempower/
