### ISSUE TITLE
Console not opening in desired directory

### ISSUE THREAD

**Issue by HPin** [ulno/ulnoiot#7]
In some cases the console does not open in the current working directory.

Instead, it opens in the basic "~>" directory without notifying the user which can lead to accidental mistakes.

**Comment by ulno** [comment]
The graver mistakes described in #5 and #6 are now caught. However this here has to be forward upstream to cloudcmd: https://github.com/coderaiser/cloudcmd

**Comment by ulno** [comment]
seems to work now and is kind of obsoleted by the user menu
